<?=$this->doctype()?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>
        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
    </head>
    <body>
        <?=$this->content?>
        <?=$this->inlineScript()?>
    </body>
</html>